# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
defaults: &defaults
  docker:
    - image: circleci/ruby:2.5.1-node-browsers
  working_directory: ~/repo

version: 2
jobs:
  the_only_job:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - "69:fe:2c:df:c8:34:c5:e6:3f:6e:18:64:43:97:58:02"
      - checkout
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}-{{ checksum "package.json" }}
      - run: 
          name: Install Rubygems if necessary
          command: |
            bundle install --path vendor/bundle --jobs 4 --retry 3
      - run: 
          name: Install Node modules if necessary 
          command: |
            cd ~/repo && npm install
      - run: 
          name: Install Rsync
          command: |
            sudo apt install rsync
      - run: 
          name: Build site
          command: |
            bundle exec jekyll build --profile --verbose --destination /home/circleci/repo/_site
      - run:
          name: Install and run Gulp
          command: |
            cd ~/repo && npx gulp
      - run: 
          name: Deploy to prod server if triggered via master branch change
          command: |
            if [ $CIRCLE_BRANCH = 'master' ]; then rsync -e "ssh -o StrictHostKeyChecking=no" -va --delete ~/repo/_site deploy@159.65.70.80:/var/www/johnathan.org/static; fi
      - run: 
          name: Bust Cloudflare cache if triggered via master branch change
          command: |
            if [ $CIRCLE_BRANCH = 'master' ]; then 
              curl -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache" \
              -H "X-Auth-Email: $CLOUDFLARE_API_EMAIL" \
              -H "X-Auth-Key: $CLOUDFLARE_API_KEY" \
              -H "Content-Type: application/json" \
              --data '{"purge_everything":true}'; 
            fi
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}-{{ checksum "package.json" }}
          paths:
            - ~/repo/vendor/bundle
            - ~/repo/node_modules

workflows:
  version: 2
  build_site:
    jobs:
      - the_only_job