# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
defaults: &defaults
  docker:
    - image: circleci/ruby:2.5.1
  working_directory: ~/repo    

version: 2
jobs:
  setup:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - "69:fe:2c:df:c8:34:c5:e6:3f:6e:18:64:43:97:58:02"
      - checkout
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle --jobs 4 --retry 3
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/repo/vendor/bundle
      - persist_to_workspace:
          root: .
          paths: vendor/bundle
  build_site:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle --path vendor/bundle
      - run: bundle exec jekyll build --profile --verbose --destination /home/circleci/repo/_site
      - persist_to_workspace:
          root: .
          paths:
            - vendor/bundle
            - _site
  test_html:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle --path vendor/bundle
      - run: bundle exec htmlproofer ./_site --check-html --checks_to_ignore 'ImageCheck' --disable-external --log_level=debug --empty_alt_ignore
  test_links:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle --path vendor/bundle
      - run: bundle exec htmlproofer ./_site --empty_alt_ignore --checks_to_ignore 'ImageCheck' --only_4xx --http-status-ignore "429" --url-ignore "/amazon.com/,/www.amazon.com/,/pro.fontawesome.com/,/amzn.to/" --log_level=debug
  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle --path vendor/bundle
      - run: sudo apt install rsync
      - run: 
          name: Deploy to prod server
          command: |
            if [ $CIRCLE_BRANCH = 'master' ]; then rsync -e "ssh -o StrictHostKeyChecking=no" -va --delete ~/repo/_site deploy@159.65.70.80:/var/www/johnathan.org/static; fi
      - run: 
          name: Bust CloudFlare cache
          command: |
            if [ $CIRCLE_BRANCH = 'master' ]; then 
              curl -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache" \
              -H "X-Auth-Email: $CLOUDFLARE_API_EMAIL" \
              -H "X-Auth-Key: $CLOUDFLARE_API_KEY" \
              -H "Content-Type: application/json" \
              --data '{"purge_everything":true}'; 
            fi


workflows:
  version: 2
  build_test_deploy:
    jobs:
      - setup
      - build_site:
          requires:
            - setup
      - test_html:
          requires:
            - build_site
      - test_links:
          requires:
            - build_site
      - deploy:
          requires:
            - test_html
            - test_links
