---
new_page_extension: md
auto_deploy: false
admin_path: "/backend/"
webhook_url: 
collections: 
upload_dir: assets/uploads
public_path: "/assets/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
